#include "protocol.h"

const QChar PROTOCOL::ADD_MESSAGE = 10;
const QChar PROTOCOL::DELETE_MESSAGE = 1;
const QChar PROTOCOL::MODIFY_MESSAGE = 2;
const QChar PROTOCOL::SET_NEW_MODERATOR = 3;
const QChar PROTOCOL::DELETE_MODERATOR = 4;
const QChar PROTOCOL::LOGIN_OK = 5;
const QChar PROTOCOL::LOGIN_DENIED = 6;
const QChar PROTOCOL::SEND_INIT_MESSAGES = 7;
const QChar PROTOCOL::USER_MODERATOR_LIST = 8;
const QChar PROTOCOL::INIT_MODERATOR = 9;
//next number is 11
